### ISSUE TITLE
Run code output does not show up in Firefox dev console

### ISSUE THREAD

**Issue by Pat-Lafon** [agentcooper/bril-playground#1]
Hello, I think I'm running the latest firefox versions, 112.0.2, but I don't see the output of any of the bril programs when pressing `Run code` with the dev console open. I am able to get the expected behavior with Chrome. Could Firefox also be supported?

**Comment by agentcooper** [comment]
Hey @Pat-Lafon, I just tried it with Firefox 112.0.2 and I see the output:

<img width="1464" alt="image" src="https://user-images.githubusercontent.com/794591/235698862-97884f6f-473b-4dd9-91bb-0a685b9dfaf2.png">

Maybe some of your extensions are messing up the page? Do you see any errors?

**Comment by Pat-Lafon** [comment]
Hmm, must be one of my extensions messing with it. Cool tool! Thanks

**Comment by agentcooper** [comment]
Sure, no problem. If you find the cause, maybe I can change the code somehow so that it does not interfere with the extension.
